name: Release Automation

on:
  release:
    types: [created]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Create ZIP for full repository
      run: zip -r KTowers_Player_Prism_Launcher.zip . -x '*.git*' '*.github*'

    - name: Create ZIP for mods folder
      run: zip -r KTowers_Player_mods.zip .minecraft/mods

    - name: Upload release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./KTowers_Player_Prism_Launcher.zip
        asset_name: KTowers_Player_Prism_Launcher.zip
        asset_content_type: application/zip

    - name: Upload mods release assets
      uses: actions/upload-release-asset@v1
      with:
        upload_url: ${{ github.event.release.upload_url }}
        asset_path: ./KTowers_Player_mods.zip
        asset_name: KTowers_Player_mods.zip
        asset_content_type: application/zip
